### ISSUE TITLE
Md5 Origin Empty

### ISSUE THREAD

**Issue by jaskaranSM** [moon004/Go-deezer-downloader#12]
Hi, I m trying to implement library support in this project but for some Reason When Downloading a track via its ID, the MD5Origin is always empty after the response, even though rest of the Song Data Struct is there,  and thus it is causing a runtime panic, any help will be appreciated, thanks.

**Comment by moon004** [comment]
@jaskaranSM 
Sorry for the late reply, but do u insert the usertoken correctly? it's working on my side (i just tested it), it should work if u clone the master branch...

**Comment by ergoz** [comment]
same problem

```
./app.exe  --id 753387942 --usertoken <my_arl_cookie>
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
main.DecryptDownload(0x0, 0x0, 0xc00018c710, 0x9, 0x819e3d, 0x1, 0x9be6c8, 0x1, 0x0, 0xc000084480, ...)
        C:/Users/ergoz/Desktop/Go-deezer-downloader-master/Utils.go:121 +0x6cd
main.GetUrlDownload(0xc0000140f0, 0x9, 0xc00007ac30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)        
        C:/Users/ergoz/Desktop/Go-deezer-downloader-master/main.go:185 +0xd54
main.main()
        C:/Users/ergoz/Desktop/Go-deezer-downloader-master/main.go:30 +0x86
```

i made  a small debug and problem with GetToken (getUserData) - it returns USER_ID - 0, that is not correct

**Comment by moon004** [comment]
Sorry for the late reply, it seems like there is an error with the login, maybe there is an login mishap.
